project_name:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: project-id
      dataset: dataset_id
      threads: 6
      job_execution_timeout_setting: 300
      priority: interactive
      retries: 1
      location: EU
    prod:
      type: bigquery
      method: oauth
      project: project-id
      dataset: dataset_id
      threads: 6
      job_execution_timeout_setting: 300
      priority: interactive
      retries: 1
      location: EU